# Generated by Django 5.0.7 on 2024-10-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('meetup_id', models.AutoField(primary_key=True, serialize=False)),
                ('meetup_name', models.CharField(max_length=30)),
                ('meetup_description', models.CharField(max_length=100)),
                ('meetup_date', models.DateField()),
                ('meetup_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('student_password', models.CharField(max_length=128)),
                ('student_phone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint.meetup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=100)),
                ('comment_created_time', models.DateTimeField(auto_now_add=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint.meetup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint.student')),
            ],
        ),
    ]
