# Generated by Django 5.0.7 on 2024-10-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
