# Generated by Django 5.0.7 on 2024-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0002_meetup_meetup_poster_alter_student_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_password', models.CharField(max_length=20)),
                ('staff_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
