# Generated by Django 5.0.7 on 2024-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
