# Generated by Django 5.0.7 on 2024-10-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0004_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
